export const courses = [
  {
    id: 1,
    title: 'React 2024. Learn React',
    nameCourse: 'React 2024. Learn React',
    nameTeacher: 'Sergey',
    imgUrl: 'https://reactjs.org/logo-og.png',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
    },
  },
  {
    id: 2,
    title: 'Angular 2024. Learn Angular',
    nameCourse: 'Angular 2024. Learn Angular',
    nameTeacher: 'Sergey',
    imgUrl: 'https://angular.io/assets/images/logos/angular/angular.svg',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
    },
  },
  {
    id: 3,
    title: 'Vue 2024. Learn Vue',
    nameCourse: 'Vue 2024. Learn Vue',
    nameTeacher: 'Sergey',
    imgUrl: 'https://vuejs.org/images/logo.png',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
    },
  },
  {
    id: 4,
    title: 'Python 2024. Learn Python',
    nameCourse: 'Python 2024. Learn Python',
    nameTeacher: 'Python',
    imgUrl: 'https://www.python.org/static/opengraph-icon-200x200.png',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
      4: 'Chapter 4',
      5: 'Chapter 5',
    },
  },
  {
    id: 5,
    title: 'React 2024. Learn React',
    nameCourse: 'React 2024. Learn React',
    nameTeacher: 'Sergey',
    imgUrl: 'https://reactjs.org/logo-og.png',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
    },
  },
  {
    id: 6,
    title: 'Angular 2024. Learn Angular',
    nameCourse: 'Angular 2024. Learn Angular',
    nameTeacher: 'Sergey',
    imgUrl: 'https://angular.io/assets/images/logos/angular/angular.svg',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
    },
  },
  {
    id: 7,
    title: 'Vue 2024. Learn Vue',
    nameCourse: 'Vue 2024. Learn Vue',
    nameTeacher: 'Sergey',
    imgUrl: 'https://vuejs.org/images/logo.png',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
    },
  },
  {
    id: 8,
    title: 'Python 2024. Learn Python',
    nameCourse: 'Python 2024. Learn Python',
    nameTeacher: 'Python',
    imgUrl: 'https://www.python.org/static/opengraph-icon-200x200.png',
    chapters: {
      1: 'Chapter 1',
      2: 'Chapter 2',
      3: 'Chapter 3',
      4: 'Chapter 4',
      5: 'Chapter 5',
    },
  },
] as const;
